title: Anant Pramanik
logo: /assets/img/Photo_Blank_BG.jpg
description:
  <p align="left" class="scroll">
    <a href="RESUME_updated.pdf">Resume</a> |
    <a href="https://www.linkedin.com/in/anantkumarpramanik/">LinkedIn</a> |
    <a href="https://github.com/AnantPramanik">GitHub</a>
    
    <br>   
    <b> 1 Domains </b>
    <br>  • Cloud Computing
    <br>  • Azure Infra Delivery
    <br>  • Migration
    <br>  • Automations
    <br>
    <b> Core Competency </b>
    <br>  • Delivery Excellence
    <br>  • Azure Cloud
    <br>  • Azure ASR
    <br>  • Scripting and Automations
    <br>  • C#
    <br>  • SQL
    <br>  • Cloud Computing
    <br>  • Microsoft Azure
    <br>  • Azure DevOps Server
    <br>  • PowerShell
    <br>  • Terraform
    <br>  • Automation
    <br>  • Windows Server
    <br>  • Microsoft Exchange
    <br>
    <br> <b> Industry Certifications </b>
    <br>  • AZ 103 Certified
    <br>
    <br> <b> Education and Experience </b>
    <br>  • Bachelor of Technology (Computer Science Engineering)
    <br>  • 5+ years of hands-on experience in
    Azure, Windows server 2012, 2016,
    PowerShell
  </p>



theme: jekyll-theme-minimal
