title: Anant Pramanik
logo: /assets/img/Photo_Blank_BG.jpg
description:
  <p align="left">
  <a href="RESUME_updated.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/anantkumarpramanik/">LinkedIn</a> |
  <a href="https://github.com/AnantPramanik">GitHub</a>
  
  <br>   
  A result-driven software professional having 5+ years of extensive hands-on experience,
  with vast experience in Cloud infra building, Migration, Monitoring, Automations, POC,
  Providing Architectural Solution and Support.
  <br>
  Well experienced in both IAAS and PAAS implementation.
  <br>
  A professional with a passion for bringing ideas to life. Proven success in understanding
  customer needs.
  <br>
  <br>
  <br>
  <br>

  </p>



theme: jekyll-theme-minimal
