title: Anant Pramanik
logo: /assets/img/Photo_Blank_BG.jpg
description:
  <p align="left" class="info-card">
    <i class="fa-sharp fa-solid fa-location-dot"></i> Noida
    <br> <i class="fa-solid fa-phone"></i> +91-8299027855
    <br> <a href="mailto:anantkumarpramanik.cs.0004@gmail.com" style="font-size:11px;color:white;"><i class="fa-solid fa-envelope"></i> anantkumarpramanik.cs.0004@gmail.com</a>
    <br> <i class="fa fa-calendar" aria-hidden="true"></i> DOB &#x3a; 18-Apr-1992 (30 years)
    <br>
  </p>
  <p align="left">
    <a href="RESUME_updated.pdf"><img src="./assets/img/pdf.png" style="width:15px;"/> Resume</a> |
    <a href="https://www.linkedin.com/in/anantkumarpramanik/"><img src="./assets/img/linkdin.png" style="width:15px;"/> LinkedIn</a> |
    <a href="https://github.com/AnantPramanik"><img src="./assets/img/github.png" style="width:15px;"/> GitHub</a>
  </p>
  <p align="left" class="scroll">
    <b> Domains </b>
    <br>  • Cloud Computing
    <br>  • Azure Infra Delivery
    <br>  • Migration
    <br>  • Automations
    <br>
    <br>
    <b> Core Competency </b>
    <br>  • Delivery Excellence
    <br>  • Azure Cloud
    <br>  • Azure ASR
    <br>  • Scripting and Automations
    <br>  • C#
    <br>  • SQL
    <br>  • Cloud Computing
    <br>  • Microsoft Azure
    <br>  • Azure DevOps Server
    <br>  • PowerShell
    <br>  • Terraform
    <br>  • Automation
    <br>  • Windows Server
    <br>  • Microsoft Exchange
    <br>
    <br> <b> Industry Certifications </b>
    <br>  • AZ 104 Certified
    <br>
    <br> <b> Education and Experience </b>
    <br>  • Bachelor of Technology (Computer Science Engineering)
    <br>  • 5+ years of hands-on experience in
    Azure, Windows server 2012, 2016,
    PowerShell
  </p>
theme: jekyll-theme-minimal
